### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-html-boilerplate-linting-and-code-style-uRxwab#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-html-boilerplate-linting-and-code-style-uRxwab/) and meets the following criteria:

- [x] The files from your last project are copied and pasted into the directory for this project
- [x] Your code returns no errors (warnings are OK) when pasted into the [W3C Validator](https://validator.w3.org/#validate_by_input) (this will also be expected for all future projects)
- [x] Consistent spacing and indentation are used on every line (this will also be expected for all future projects)
- [x] `skeleton.css` is used to improve the design of the page

- It's still not a blog. Can fix that if you want.
- The skeleton.css is there, but it didn't actually change the website layout at all.

**Comment by chrisvfritz** [comment]
Looks good! Though I have to say the flashing text drove me a little crazy. 😛  I don't care about it being a blog specifically, but the reason `skeleton.css` isn't working is because of a [tiny typo on this line](https://github.com/lordcrekit/MI-449-SS17-740-html-boilerplate-linting-and-code-style-uRxwab/blob/master/index.html#L8): `type="text/cass"` should be `type="text/css"`. Can you fix that?

**Comment by lordcrekit** [comment]
oops- Fixed.

**Comment by chrisvfritz** [comment]
Beautiful! 🎉 :shipit:
